globals:
  default_workspace_dir: "${DEFAULT_WORKSPACE_DIR}"   # e.g. ./workspace
  default_go_version:    "${DEFAULT_GO_VERSION}"      # e.g. 1.24

assets:
  sing-box:
    workspace:        "${WORKSPACE_DIR}"
    url:              "https://github.com/sagernet/sing-box.git"
    build_go_version: "${SB_GO_VERSION}"
    build_commits:    "${SB_COMMITS}"      # comma
    build_branches:   "${SB_BRANCHES}"     # comma
    build_platforms:  "${SB_PLATFORMS}"    # comma linux/amd64,etc.
    build_tags:       "${SB_TAGS}"         # e.g. with_gvisor,with_quic
    build_ldflags:    "${SB_LDFLAGS}"      # may contain ${SHORT_SHA}/${VERSION_TAG}
    envs:             "${SB_EXTRA_ENVS}"   # KEY=VAL,KEY2=VAL2

  xray-core:
    workspace:        "${WORKSPACE_DIR}"
    url:              "https://github.com/XTLS/Xray-core.git"
    build_go_version: "${XR_GO_VERSION}"
    build_commits:    "${XR_COMMITS}"
    build_branches:   "${XR_BRANCHES}"
    build_platforms:  "${XR_PLATFORMS}"
    build_tags:       "${XR_TAGS}"
    build_ldflags:    "${XR_LDFLAGS}"
    envs:             "${XR_EXTRA_ENVS}"