name: Matrix Build

on:
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      extra_envs:
        description: "EXTRA_ENVS: KEY=VAL,KEY2=VAL2"
        required: false
        default: ''
  push:
   branches-ignore:
     - '*'

env:
  DEFAULT_WORKSPACE_DIR: workspace
  DEFAULT_GO_VERSION:   1.24.4
  WORKSPACE_DIR:        workspace


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          include:
            - repo:   sing-box
              url:    https://github.com/sagernet/sing-box.git
              refs:   dev-next,main-next
              plats:  linux/amd64,linux/arm64,windows/amd64
              gover:  1.23.1
              tags:   'with_gvisor,with_quic,with_utls,with_clash_api'
              ldf:    '-X github.com/sagernet/sing-box/constant.Version=${VERSION_TAG} -s -w -buildid='
              extra:  ''
            - repo:   xray-core
              url:    https://github.com/XTLS/Xray-core.git
              refs:   main
              plats:  linux/amd64,linux/arm64,windows/amd64
              gover:  1.24.4
              tags:   ''
              ldf:    '-X github.com/xtls/xray-core/core.build=${SHORT_SHA} -s -w -buildid='
              extra:  ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - if: ${{ github.event.inputs.extra_envs != '' }}
        run: |
          echo "Setting extra environment variables"
          echo "${{ github.event.inputs.extra_envs }}" | tr ',' '\n' >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.gover }}

      - name: Build matrix refs / plats
        shell: bash
        run: |
          set -ex
          IFS=',' read -ra REFARR  <<<"${{ matrix.refs }}"
          IFS=',' read -ra PLATARR <<<"${{ matrix.plats }}"
          for REF in "${REFARR[@]}"; do
            for P in "${PLATARR[@]}"; do
              echo "::group::${{ matrix.repo }}  $REF  $P"
              env \
                REPO="${{ matrix.repo }}" \
                REPO_URL="${{ matrix.url }}" \
                REF="$REF" \
                PLATFORM="$P" \
                BUILD_TAGS="${{ matrix.tags }}" \
                BUILD_LDFLAGS="${{ matrix.ldf }}" \
                EXTRA_ENVS="${{ matrix.extra }}" \
                go run main.go
              echo "::endgroup::"
            done
          done

      - name: Upload raw-binaries
        uses: actions/upload-artifact@v4
        with:
          name: raw-binaries
          path: workspace/**/artifacts/**

      - name: Export ref-platform list
        id: matrixgen
        shell: bash
        run: |
          set -eu
          JSON="[]"
          for repo in "${{ matrix.repo }}"; do
            if [ ! -d "workspace/$repo" ]; then continue; fi
            for ref in $(ls workspace/$repo); do
              for plat in $(ls workspace/$repo/$ref); do
                JSON=$(jq -c \
                  --arg r "$repo" --arg ref "$ref" --arg plat "$plat" \
                  '. += [{"repo":$r,"ref":$ref,"plat":$plat}]' \
                  <<<"$JSON")
              done
            done
          done
          echo "matrix=$JSON" >> "$GITHUB_OUTPUT"
    outputs:
        matrix: ${{ steps.matrixgen.outputs.matrix }}


  upload:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build.outputs.matrix) }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: raw-binaries

      - name: Flatten binary
        shell: bash
        run: |
          set -eu
          SRC="${{ matrix.repo }}/${{ matrix.ref }}/${{ matrix.plat }}/${{ matrix.repo }}"
          OUT="${{ matrix.repo }}-${{ matrix.ref }}-${{ matrix.plat }}"
          [[ "${{ matrix.plat }}" == windows/* ]] && OUT="${OUT}.exe"
          cp "$SRC" "$OUT"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.repo }}-${{ matrix.ref }}-${{ matrix.plat }}
          path: ${{ matrix.repo }}-${{ matrix.ref }}-${{ matrix.plat }}*
